<?php
require 'vendor/parse/php-sdk/autoload.php';
require_once 'analytics.php';
require_once 'mail/send.php';
use Parse\ParseClient;
use Parse\ParseObject;
use Parse\ParseQuery;


function analytics01_menu() {

    /*
     * ******* /my_module/cc
     */
    $items = array();

    $items['custom/analytics01'] = array(
        'title' => 'Analytics01',
        'page callback' => 'analytics01_con',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function analytics01_con() {

    ParseClient::initialize('P60EfTUuOZoeZyD2qSLpOrc8DWwUk2YjEqU2HY1R', 's3b2cfGtQhSFYM16ZIJQ7yXioTjt35Um5mn9SyP8', '3jz6CONqt5psS4UlGu3RB28ldIw311Iv2I8eA3Mh');
    drupal_add_js(drupal_get_path('module', 'analytics01') . "/Chart.js");
    drupal_add_js(drupal_get_path('module', 'analytics01') . "/ga.js");
    drupal_add_js(drupal_get_path('module', 'analytics01') . "/jquery.js");
    drupal_add_js(drupal_get_path('module', 'analytics01') . "/MyJs/infoTraffic.js");
    drupal_add_js(drupal_get_path('module', 'analytics01') . "/MyJs/infoArticle.js");

    $vars = "";

    $lastTraffic = getLastXTraffic(4);

    $node = infoArticle("Paratus Sed");


    $tagU = getTagUser(4);




    $vars .= "<h3> Traffic Statistics: </h3>";

    $vars .= "
            <p><b>Select the days to analyze:</b></p>
            <form>
            Days: <input type=\"text\" onkeyup=\"showDays(this.value)\">
            </form>
            <p id='hintText'><span id=\"hint\"></span></p>";

    $vars .= "<canvas id=\"updating-chart\" width=\"500\" height=\"300\"></canvas>";


    $vars .= "<h3>Per article Statistics: </h3>";
    $vars .= "<p><b>Select the Article to analyse:</b></p>
            <form>
            Select Article: <input type=\"text\" onkeyup=\"showArticle(this.value)\">
            </form>
            <p><span id=\"hintArticle\"></span></p>";

    $vars .= "<canvas id='updating-chart-Article' width='500' height='300'></canvas>";


    $vars .= "<input type='button' onclick='newsLetter()' value='Send NewsLetter'>";


    /*
     *
     *
     *
     *
     *
     *
     *                          COMMENT HERE
     *
     *
     *
     *
     *
     */

/*
    $users = db_query("SELECT uid, mail, name FROM users");
    $oneWeekAgo =  time()-(60*60*24*7);
    $articles = db_query("SELECT nid, title FROM node WHERE type='article' AND created>'" . $oneWeekAgo . "' ORDER BY created");

    foreach ($users as $user) {
        $tags = getTagUser($user->uid);


        $toSend = Array();

        foreach ($tags as $key => $value){

            $articles = db_query("SELECT nid, title FROM node WHERE type='article' AND created>'" . $oneWeekAgo . "' ORDER BY created");
            foreach($articles as $article){

                $newArticleTags = getTag($article->title);

                foreach($newArticleTags as $arTag => $numTag){
                    echo $key . "    vs    " . $arTag ."<br>";
                    if($arTag == $key){
                        if(!in_array($article->nid, $toSend)){
                            array_push($toSend, $article->nid);
                        }
                    }
                }
            }
        }

        $message = "
            <!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">
            <html xmlns=\"http://www.w3.org/1999/xhtml\">
             <head>
              <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />
              <title>Demystifying Email Design</title>
              <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>
            </head>
            <body style=\"margin: 0; padding: 0;\">
            <div style=\"padding:0;margin:0;background:#6e797f  repeat 50%;width:100%;display:block\">
               <!--[if mso]>
               <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"width:100%;display:block;margin:0 auto;border:none;\" width=\"100%\" >
                  <tr>
                     <td>
                        <![endif]-->
                        <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"width:100%;margin:0 auto;border:none;table-layout:fixed;height:0px;\" height=\"0\">
                           <tbody>
                              <tr>
                                 <td style=\"width:100%;background-color:transparent;height:0px\" height=\"0\">
                                    <!--[if mso]>
                                    <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" height=\"0\" style=\"width:640px;display:block;margin:0 auto;border:none;\" width=\"640\">
                                       <tr>
                                          <td>
                                             <![endif]-->
                                             <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" height=\"0\" style=\"width:100%;margin:0 auto;border:none;max-width:640px;table-layout:fixed;height:0px\">
                                                <tbody style=\"width:100%;\">
                                                   <tr class=\"blockClass\">
                                                      <td style=\"height:0px;background-color:transparent;\" height=\"0\"></td>
                                                   </tr>
                                                </tbody>
                                             </table>
                                             <!--[if mso]>
                                          </td>
                                       </tr>
                                    </table>
                                    <![endif]-->
                                 </td>
                              </tr>
                           </tbody>
                        </table>
                        <!--[if mso]>
                        <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"width:640px;display:block;margin:0 auto;border:none;\" width=\"640\">
                           <tr>
                              <td>
                                 <![endif]-->
                                 <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"width:100%;display:block;margin:0 auto;border:none;max-width:640px;table-layout:fixed;\">
                                    <tbody style=\"width:100%;display:block;\">
                                       <tr class=\"holderMax blockClass \" style=\"width:640px;display:block\">
                                          <td class=\"blockClassPadding \" style=\"background-color:transparent;width:100%;display:block\">
                                             <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" class=\"layout_width_100_00  cellFull\" style=\"display:block;width:640px;border:none !important;\">
                                                <tbody style=\"width:100%;display:block\">
                                                   <tr style=\"display:block;width:100%;\">
                                                      <td style=\" vertical-align:top;text-align:center;width:640px;  background-color:transparent; overflow:hidden;display:block;\" class=\"cellFull  layout_width_100   outlook_width_640 \">
                                                         <table para=\"complexContainerBorder\" class=\"outlook_width_640 \" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"display:block!important\">
                                                            <tbody style=\"width:100%;display:block\">
                                                               <tr style=\"width:100%;display:block;\">
                                                                  <td class=\"outlook_width_640   wild_full  text_padding_0 \" style=\"border-collapse:collapse;vertical-align:top;padding:8px 0px 8px 0px;background-color:transparent;max-width:640px;display:inline-block;\">
                                                                     <table class=\"cellFull chromeFix\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"width:100%;max-width:640px\">
                                                                        <tbody class=\"smallFull\">
                                                                           <tr style=\"width:100%;\" class=\"smallFull\">
                                                                              <td class=\"text_padding_mobile_0 cellFull  noMoreHeight\" align=\"center\" style=\"width:100%;border-collapse: collapse;text-align:center;height:20px;vertical-align:middle\">
                                                                                 <div style=\"text-align:center;font-size:11px;font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#adb8bd;line-height:100%;width:100%;;display: block !important;\">Email not displaying correctly? <a href=\"#0\" typ=\"2\" style=\"color: #009de0; text-decoration: none;\"><span>View it in your browser.</span></a></div>
                                                                              </td>
                                                                           </tr>
                                                                        </tbody>
                                                                     </table>
                                                                  </td>
                                                               </tr>
                                                            </tbody>
                                                         </table>
                                                      </td>
                                                   </tr>
                                                </tbody>
                                             </table>
                                          </td>
                                       </tr>
                                    </tbody>
                                 </table>
                                 <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"width:100%;display:block;margin:0 auto;border:none;max-width:640px;table-layout:fixed;\">
                                    <tbody style=\"width:100%;display:block;\">
                                       <tr class=\"holderMax blockClass \" style=\"width:640px;display:block\">
                                          <td class=\"blockClassPadding \" style=\"background-color:#fff;width:100%;display:block\">
                                             <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" class=\"layout_width_100_00  cellFull\" style=\"display:block;width:640px;border:none !important;\">
                                                <tbody style=\"width:100%;display:block\">
                                                   <tr style=\"display:block;width:100%;\">
                                                      <td style=\"width:640px;  background-color:#fff; overflow:hidden;\" class=\"cellFull  layout_width_100   outlook_width_640 \"><img src=\"http://drupal7jfmtestaqczpeqfxp.devcloud.acquia-sites.com/sites/all/themes/subtheme/logo.png\" alt=\"Download images\" style=\"border:none;display:block;width:100%;height:auto;background-color:transparent;text-align:start;font-size:12px;font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#686868;line-height:10%;;\"></td>
                                                   </tr>
                                                </tbody>
                                             </table>
                                          </td>
                                       </tr>
                                    </tbody>
                                 </table>
                                 <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"width:100%;display:block;margin:0 auto;border:none;max-width:640px;table-layout:fixed;\">
                                    <tbody style=\"width:100%;display:block;\">
                                       <tr class=\"blockClass holderMax\" style=\"width:640px;display:block\">
                                          <td class=\"blockClassPadding\" style=\"width:100%;display:block;vertical-align:middle;padding:0px;background-color:#fff;\">
                                             <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"border: none; display: block;min-height:68px\">
                                                <tbody style=\"width:100%;display:block\">
                                                   <tr style=\"width:100%;display:block\">
                                                      <td style=\"width:50px;background-color:#fff;\" class=\"out_hide\"></td>
                                                      <td style=\" vertical-align:top;text-align:center;width:540px;  background-color:transparent; overflow:hidden;\" class=\"cellFull  layout_width_84_37   outlook_width_540 \">
                                                         <table para=\"complexContainerBorder\" class=\"outlook_width_540 \" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"display:block!important\">
                                                            <tbody style=\"width:100%;display:block\">
                                                               <tr style=\"width:100%;display:block;\">
                                                                  <td class=\"outlook_width_540   wild_full  text_padding_0 \" style=\"border-collapse:collapse;vertical-align:top;padding:8px 0px 8px 0px;background-color:transparent;max-width:540px;display:inline-block;\">
                                                                     <table class=\"cellFull chromeFix\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"width:100%;max-width:540px\">
                                                                        <tbody class=\"smallFull\">
                                                                           <tr style=\"width:100%;\" class=\"smallFull\">
                                                                              <td class=\"text_padding_mobile_0 cellFull  noMoreHeight\" align=\"center\" style=\"width:100%;border-collapse: collapse;text-align:center;height:52px;vertical-align:top\">
                                                                                 <div style=\"text-align:center;font-size:40px;font-family: Roboto Slab Thin , Arial, Helvetica, serif;text-decoration:none;color:#000;line-height:130%;width:100%;;display: block !important;\">Last Articles</div>
                                                                              </td>
                                                                           </tr>
                                                                        </tbody>
                                                                     </table>
                                                                  </td>
                                                               </tr>
                                                            </tbody>
                                                         </table>
                                                      </td>
                                                      <td style=\"width:50px;background-color:#fff;\" class=\"out_hide\"></td>
                                                   </tr>
                                                </tbody>
                                             </table>
                                          </td>
                                       </tr>
                                    </tbody>
                                 </table>
                                 <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"width:100%;display:block;margin:0 auto;border:none;max-width:640px;table-layout:fixed;\">
                                    <tbody style=\"width:100%;display:block;\">
                                       <tr class=\"blockClass holderMax\" style=\"width:640px;display:block\">
                                          <td class=\"blockClassPadding\" style=\"width:100%;display:block;vertical-align:middle;padding:0px;background-color:#fff;\">
                                             <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"border: none; display: block;min-height:65px\">
                                                <tbody style=\"width:100%;display:block\">
                                                   <tr style=\"width:100%;display:block\">
                                                      <td style=\"width:50px;background-color:#fff;\" class=\"out_hide\"></td>
                                                      <td style=\" vertical-align:top;text-align:center;width:540px;  background-color:transparent; overflow:hidden;\" class=\"cellFull  layout_width_84_37   outlook_width_540 \">
                                                         <table para=\"complexContainerBorder\" class=\"outlook_width_540 \" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"display:block!important\">
                                                            <tbody style=\"width:100%;display:block\">
                                                               <tr style=\"width:100%;display:block;\">
                                                                  <td class=\"outlook_width_540   wild_full  text_padding_0 \" style=\"border-collapse:collapse;vertical-align:top;padding:8px 0px 8px 0px;background-color:transparent;max-width:540px;display:inline-block;\">
                                                                     <table class=\"cellFull chromeFix\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"width:100%;max-width:540px\">
                                                                        <tbody class=\"smallFull\">
                                                                           <tr style=\"width:100%;\" class=\"smallFull\">
                                                                              <td class=\"text_padding_mobile_0 cellFull  noMoreHeight\" align=\"center\" style=\"width:100%;border-collapse: collapse;text-align:center;height:49px;vertical-align:top\">
                                                                                 <div style=\"text-align:center;font-size:14px;font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#000;line-height:140%;width:100%;;display: block !important;\">12-15.07.2015</div>
                                                                              </td>
                                                                           </tr>
                                                                        </tbody>
                                                                     </table>
                                                                  </td>
                                                               </tr>
                                                            </tbody>
                                                         </table>
                                                      </td>
                                                      <td style=\"width:50px;background-color:#fff;\" class=\"out_hide\"></td>
                                                   </tr>
                                                </tbody>
                                             </table>
                                          </td>
                                       </tr>
                                    </tbody>
                                 </table>
                                 <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"width:100%;display:block;margin:0 auto;border:none;max-width:640px;table-layout:fixed;\">
                                    <tbody style=\"width:100%;display:block;\">
                                       <tr class=\"blockClass holderMax\" style=\"width:640px;display:block\">
                                          <td class=\"blockClassPadding\" style=\"width:100%;display:block;vertical-align:middle;padding:0px;background-color:#F0E7E4;\">
                                             <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"border: none; display: block;min-height:94px\">
                                                <tbody style=\"width:100%;display:block\">
                                                   <tr style=\"width:100%;display:block\">
                                                      <td style=\"width:50px;background-color:##F0E7E4;\" class=\"out_hide\"></td>
                                                      <td style=\" vertical-align:top;text-align:center;width:540px;  background-color:transparent; overflow:hidden;\" class=\"cellFull  layout_width_84_37   outlook_width_540 \">
                                                         <table para=\"complexContainerBorder\" class=\"outlook_width_540 \" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"display:block!important\">
                                                            <tbody style=\"width:100%;display:block\">
                                                               <tr style=\"width:100%;display:block;\">
                                                                  <td class=\"outlook_width_540   wild_full  text_padding_0 \" style=\"border-collapse:collapse;vertical-align:top;padding:8px 0px 8px 0px;background-color:transparent;max-width:540px;display:inline-block;\">
                                                                     <table class=\"cellFull chromeFix\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"width:100%;max-width:540px\">
                                                                        <tbody class=\"smallFull\">
                                                                           <tr style=\"width:100%;\" class=\"smallFull\">
                                                                              <td class=\"text_padding_mobile_0 cellFull  noMoreHeight\" align=\"center\" style=\"width:100%;border-collapse: collapse;text-align:center;height:78px;vertical-align:bottom\">
                                                                                 <div style=\"text-align:center;font-size:30px;font-family: Roboto Slab , Arial, Helvetica, serif;text-decoration:none;color:#3e494f;line-height:130%;width:100%;;display: block !important;\">From our blog</div>
                                                                              </td>
                                                                           </tr>
                                                                        </tbody>
                                                                     </table>
                                                                  </td>
                                                               </tr>
                                                            </tbody>
                                                         </table>
                                                      </td>
                                                      <td style=\"width:50px;background-color:##F0E7E4;\" class=\"out_hide\"></td>
                                                   </tr>
                                                </tbody>
                                             </table>
                                          </td>
                                       </tr>
                                    </tbody>
                                 </table>

                                 <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"width:100%;margin:0 auto;border:none;max-width:640px;table-layout:fixed;\">
                                    <tbody style=\"width:100%;\">
                                       <tr class=\"blockClass\" style=\"\">
                                          <td style=\"height:60px;background-color:#F0E7E4;  \"></td>
                                       </tr>
                                    </tbody>
                                 </table>
                                 ";

                                for($i=0; $i<4; $i++){
                                    $node  = node_load($toSend[$i]);
                                    $message .= "
                                        <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"width:100%;display:block;margin:0 auto;border:none;max-width:640px;table-layout:fixed;\">
                                    <tbody style=\"width:100%;display:block;\">
                                       <tr class=\"blockClass holderMax\" style=\"width:640px;display:block\">
                                          <td class=\"blockClassPadding\" style=\"width:100%;display:block;vertical-align:middle;padding:0px;background-color:#F0E7E4;\">
                                             <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"border: none; display: block;\">
                                                <tbody style=\"width:100%;display:block\">
                                                   <tr style=\"width:100%;display:block\">
                                                      <td style=\"width:50px;background-color:#F0E7E4;\" class=\"out_hide\"></td>
                                                      <td class=\"cellFull layout_width_39_84 \" style=\" vertical-align:top;width:255px; padding:0px;background-color:transparent;\" bgcolor=\"transparent\">
                                                         <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"display:block;\">
                                                            <tbody style=\"width:100%;display:block\">
                                                               <tr style=\"width:100%;display:block;\">
                                                                  <td class=\"outlook_width_255  noWidthMax \" style=\"max-width:255px;min-height:355px;border:none;;border-collapse: collapse;vertical-align:top;display:block;background-color:transparent;\">
                                                                     <table class=\"cellFull\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"display:block;border-collapse:collapse;;max-width:255px;width:100%\">
                                                                        <tbody class=\"cellFull\" style=\"width:100%;display:block\">
                                                                           <tr class=\"cellFull\" style=\"width:100%;display:block\">
                                                                              <td class=\"cellFull noMoreHeight  \"><img src=\"http://drupal7jfmtestaqczpeqfxp.devcloud.acquia-sites.com/sites/default/files/styles/slideshow/public/field/image/\". $node->field_image['und'][0]['filename'] . "\" alt=\"Download images\" style=\"border:none;display:block;width:100%;height:auto;background-color:transparent;text-align:start;font-size:12px;font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#686868;line-height:100%;;\"></td>
                                                                           </tr>
                                                                           <tr class=\"cellFull\" style=\"width:100%;display:block\">
                                                                              <td class=\"cellFull noMoreHeight  outlook_height_62 \" style=\"min-height:62px;vertical-align:top;width:100%;display:block\">
                                                                                 <table para=\"paddingContainer\" class=\"cellFull chromeFix\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"max-width:255px;width:100%;border:none !important;text-align:left;table-layout:fixed\">
                                                                                    <tbody class=\"smallFull\">
                                                                                       <tr style=\"width:100%;\" class=\"smallFull\">
                                                                                          <td class=\"cellFull  text_padding_0 \" style=\"max-width:255px;padding:8px 0px 8px 0px;\">
                                                                                             <div style=\"text-align:left;font-size:18px;font-family: Roboto Slab , Arial, Helvetica, serif;text-decoration:none;color:#3e494f;line-height:129%;;display: block !important;\">". $node->title .".</div>
                                                                                          </td>
                                                                                       </tr>
                                                                                    </tbody>
                                                                                 </table>
                                                                              </td>
                                                                           </tr>
                                                                           <tr class=\"cellFull\" style=\"width:100%;display:block\">
                                                                              <td class=\"cellFull noMoreHeight  outlook_height_104 \" style=\"min-height:104px;vertical-align:top;width:100%;display:block\">
                                                                                 <table para=\"paddingContainer\" class=\"cellFull chromeFix\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"max-width:255px;width:100%;border:none !important;text-align:left;table-layout:fixed\">
                                                                                    <tbody class=\"smallFull\">
                                                                                       <tr style=\"width:100%;\" class=\"smallFull\">
                                                                                          <td class=\"cellFull  text_padding_0 \" style=\"max-width:255px;padding:8px 0px 8px 0px;\">
                                                                                             <div style=\"text-align:left;font-size:14px;font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#adb8bd;line-height:159%;;display: block !important;\">Ut molestie a, ultricies porta urna. Vestibulu commodo volutpat a, convallis ac, laoreet enim. Phasellus fermentum in, dolor.</div>
                                                                                          </td>
                                                                                       </tr>
                                                                                    </tbody>
                                                                                 </table>
                                                                              </td>
                                                                           </tr>
                                                                           <tr class=\"cellFull\" style=\"width:100%;display:block\">
                                                                              <td class=\"cellFull noMoreHeight  outlook_height_48 \" style=\"min-height:48px;vertical-align:top;width:100%;display:block\" align=\"left\">
                                                                                 <table para=\"paddingContainer\" class=\"cellFull chromeFix\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"max-width:255px;width:100%;border:none !important;text-align:left;table-layout:fixed\">
                                                                                    <tbody class=\"smallFull\">
                                                                                       <tr style=\"width:100%;\" class=\"smallFull\">
                                                                                          <td class=\"cellFull  text_padding_0 \" style=\"max-width:255px;padding:8px 0px 8px 0px;\">
                                                                                             <div>
                                                                                                <!--[if mso]>
                                                                                                <v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\"  xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"#0\" style=\"height:32px;v-text-anchor:middle;width:123px;\" arcsize=\"18.75%\" fillcolor=\"#66c9ff\" strokeweight=\"0px\" stroke=\"f\">
                                                                                                   <w:anchorlock/>
                                                                                                   <center style=\"text-align:center;font-size:12px;font-family: Roboto Slab , Arial, Helvetica, serif;text-decoration:none;color:#ffffff;line-height:100%;\">Read more</center>
                                                                                                </v:roundrect>
                                                                                                <![endif]--><a href=\"#0\" style=\"background-color:#66c9ff;display:inline-block;text-align:center;font-size:12px;font-family: Roboto Slab , Arial, Helvetica, serif;text-decoration:none;color:#ffffff;line-height:100%;border-bottom-left-radius:6px;-webkit-border-bottom-left-radius:6px;border-bottom-right-radius:6px;-webkit-border-bottom-right-radius:6px;border-top-left-radius:6px;-webkit-border-top-left-radius:6px;border-top-right-radius:6px;-webkit-border-top-right-radius:6px;;padding:10px 31px 10px 31px;;-webkit-text-size-adjust:none;mso-hide:all;\">Read more</a>
                                                                                             </div>
                                                                                          </td>
                                                                                       </tr>
                                                                                    </tbody>
                                                                                 </table>
                                                                              </td>
                                                                           </tr>
                                                                        </tbody>
                                                                     </table>
                                                                  </td>
                                                               </tr>
                                                            </tbody>
                                                         </table>
                                                      </td>
                                                   </tr>
                                                </tbody>
                                             </table>
                                          </td>
                                       </tr>
                                    </tbody>
                                 </table>
                                    ";
                                }
                                 $message .="
                                 <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"width:100%;margin:0 auto;border:none;max-width:640px;table-layout:fixed;\">
                                    <tbody style=\"width:100%;\">
                                       <tr class=\"blockClass\" style=\"\">
                                          <td style=\"height:60px;background-color:#F0E7E4;  \"></td>
                                       </tr>
                                    </tbody>
                                 </table>
                                 <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"width:100%;display:block;margin:0 auto;border:none;max-width:640px;table-layout:fixed;\">
                                    <tbody style=\"width:100%;display:block;\">
                                       <tr class=\"blockClass holderMax\" style=\"width:640px;display:block\">
                                          <td class=\"blockClassPadding\" style=\"width:100%;display:block;vertical-align:middle;padding:0px;background-color:#F0E7E4;\">
                                             <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"border: none; display: block;min-height:112px\">
                                                <tbody style=\"width:100%;display:block\">
                                                   <tr style=\"width:100%;display:block\">
                                                      <td style=\"width:50px;background-color:#F0E7E4;\" class=\"out_hide\"></td>
                                                      <td style=\" vertical-align:top;text-align:center;width:540px;  background-color:transparent; overflow:hidden;\" class=\"cellFull  layout_width_84_37   outlook_width_540 \">
                                                         <table para=\"complexContainerBorder\" class=\"outlook_width_540 \" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"display:block!important\">
                                                            <tbody style=\"width:100%;display:block\">
                                                               <tr style=\"width:100%;display:block;\">
                                                                  <td class=\"outlook_width_540   wild_full  text_padding_0 \" style=\"border-collapse:collapse;vertical-align:top;padding:8px 0px 8px 0px;background-color:transparent;max-width:540px;display:inline-block;\">
                                                                     <table class=\"cellFull chromeFix\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"width:100%;max-width:540px\">
                                                                        <tbody class=\"smallFull\">
                                                                           <tr style=\"width:100%;\" class=\"smallFull\">
                                                                              <td class=\"text_padding_mobile_0 cellFull  noMoreHeight\" align=\"center\" style=\"width:100%;border-collapse: collapse;text-align:center;height:96px;vertical-align:bottom\">
                                                                                 <div style=\"text-align:center;font-size:28px;font-family: Roboto Slab , Arial, Helvetica, serif;text-decoration:none;color:#3e494f;line-height:130%;width:100%;;display: block !important;\">Try with your Smartphone&nbsp;</div>
                                                                              </td>
                                                                           </tr>
                                                                        </tbody>
                                                                     </table>
                                                                  </td>
                                                               </tr>
                                                            </tbody>
                                                         </table>
                                                      </td>
                                                      <td style=\"width:50px;background-color:#F0E7E4;\" class=\"out_hide\"></td>
                                                   </tr>
                                                </tbody>
                                             </table>
                                          </td>
                                       </tr>
                                    </tbody>
                                 </table>
                                 <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"width:100%;display:block;margin:0 auto;border:none;max-width:640px;table-layout:fixed;\">
                                    <tbody style=\"width:100%;display:block;\">
                                       <tr class=\"blockClass holderMax\" style=\"width:640px;display:block\">
                                          <td class=\"blockClassPadding\" style=\"width:100%;display:block;vertical-align:middle;padding:0px;background-color:#F0E7E4;\">
                                             <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"border: none; display: block;min-height:37px\">
                                                <tbody style=\"width:100%;display:block\">
                                                   <tr style=\"width:100%;display:block\">
                                                      <td style=\"width:50px;background-color:#F0E7E4;\" class=\"out_hide\"></td>
                                                      <td style=\" vertical-align:top;text-align:center;width:540px;  background-color:transparent; overflow:hidden;\" class=\"cellFull  layout_width_84_37   outlook_width_540 \">
                                                         <table para=\"complexContainerBorder\" class=\"outlook_width_540 \" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"display:block!important\">
                                                            <tbody style=\"width:100%;display:block\">
                                                               <tr style=\"width:100%;display:block;\">
                                                                  <td class=\"outlook_width_540   wild_full  text_padding_0 \" style=\"border-collapse:collapse;vertical-align:top;padding:2px 0px 2px 0px;background-color:transparent;max-width:540px;display:inline-block;\">
                                                                     <table class=\"cellFull chromeFix\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"width:100%;max-width:540px\">
                                                                        <tbody class=\"smallFull\">
                                                                           <tr style=\"width:100%;\" class=\"smallFull\">
                                                                              <td class=\"text_padding_mobile_0 cellFull  noMoreHeight\" align=\"center\" style=\"width:100%;border-collapse: collapse;text-align:center;height:33px;vertical-align:top\">
                                                                                 <div style=\"text-align:center;font-size:14px;font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#adb8bd;line-height:150%;width:100%;;display: block !important;\">It's Responsive.</div>
                                                                              </td>
                                                                           </tr>
                                                                        </tbody>
                                                                     </table>
                                                                  </td>
                                                               </tr>
                                                            </tbody>
                                                         </table>
                                                      </td>
                                                      <td style=\"width:50px;background-color:#F0E7E4;\" class=\"out_hide\"></td>
                                                   </tr>
                                                </tbody>
                                             </table>
                                          </td>
                                       </tr>
                                    </tbody>
                                 </table>
                                 <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"width:100%;display:block;margin:0 auto;border:none;max-width:640px;table-layout:fixed;\">
                                    <tbody style=\"width:100%;display:block;\">
                                       <tr class=\"holderMax blockClass \" style=\"width:640px;display:block\">
                                          <td class=\"blockClassPadding \" style=\"background-color:#ffffff;width:100%;display:block\">
                                             <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" class=\"layout_width_100_00  cellFull\" style=\"display:block;width:640px;border:none !important;\">
                                                <tbody style=\"width:100%;display:block\">
                                                   <tr style=\"display:block;width:100%;\">
                                                      <td style=\"width:640px;  background-color:#ffffff; overflow:hidden;\" class=\"cellFull  layout_width_100   outlook_width_640 \"><img src=\"http://www.classcrowd.altervista.org/img/phpbaFSIM.png\" alt=\"Download images\" style=\"border:none;display:block;width:100%;height:auto;background-color:transparent;text-align:start;font-size:12px;font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#686868;line-height:10%;;\"></td>
                                                   </tr>
                                                </tbody>
                                             </table>
                                          </td>
                                       </tr>
                                    </tbody>
                                 </table>
                                 <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"width:100%;display:block;margin:0 auto;border:none;max-width:640px;table-layout:fixed;\">
                                    <tbody style=\"width:100%;display:block;\">
                                       <tr class=\"blockClass holderMax\" style=\"width:640px;display:block\">
                                          <td class=\"blockClassPadding\" style=\"width:100%;display:block;vertical-align:middle;padding:0px;background-color:#3e494f;\">
                                             <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"border: none; display: block;min-height:87px\">
                                                <tbody style=\"width:100%;display:block\">
                                                   <tr style=\"width:100%;display:block\">
                                                      <td style=\"width:50px;background-color:#3e494f;\" class=\"out_hide\"></td>
                                                      <td style=\" vertical-align:top;text-align:left;width:255px;  background-color:transparent; overflow:hidden;\" class=\"cellFull  layout_width_39_84   outlook_width_255 \">
                                                         <table para=\"complexContainerBorder\" class=\"outlook_width_255 \" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"display:block!important\">
                                                            <tbody style=\"width:100%;display:block\">
                                                               <tr style=\"width:100%;display:block;\">
                                                                  <td class=\"outlook_width_255   wild_full superWidthClass text_padding_0 \" style=\"border-collapse:collapse;vertical-align:top;padding:8px 0px 8px 0px;background-color:transparent;max-width:255px;display:inline-block;\">
                                                                     <table class=\"cellFull chromeFix\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"width:100%;max-width:255px\">
                                                                        <tbody class=\"smallFull\">
                                                                           <tr style=\"width:100%;\" class=\"smallFull\">
                                                                              <td class=\"text_padding_mobile_0 cellFull  noMoreHeight\" align=\"left\" style=\"width:100%;border-collapse: collapse;text-align:left;height:71px;vertical-align:bottom\">
                                                                                 <div style=\"text-align:left;font-size:18px;font-family: Roboto Slab , Arial, Helvetica, serif;text-decoration:none;color:#ffffff;line-height:100%;width:100%;;display: block !important;\">About us</div>
                                                                              </td>
                                                                           </tr>
                                                                        </tbody>
                                                                     </table>
                                                                  </td>
                                                               </tr>
                                                            </tbody>
                                                         </table>
                                                      </td>
                                                      <td style=\"width:30px;background-color:#3e494f;\" class=\"out_hide\"></td>
                                                      <td style=\" vertical-align:top;text-align:left;width:255px;  background-color:transparent; overflow:hidden;\" class=\"cellFull  layout_width_39_84   outlook_width_255 \">
                                                         <table para=\"complexContainerBorder\" class=\"outlook_width_255 \" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"display:block!important\">
                                                            <tbody style=\"width:100%;display:block\">
                                                               <tr style=\"width:100%;display:block;\">
                                                                  <td class=\"outlook_width_255   wild_full superWidthClass text_padding_0 \" style=\"border-collapse:collapse;vertical-align:top;padding:8px 0px 8px 0px;background-color:transparent;max-width:255px;display:inline-block;\">
                                                                     <table class=\"cellFull chromeFix\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"width:100%;max-width:255px\">
                                                                        <tbody class=\"smallFull\">
                                                                           <tr style=\"width:100%;\" class=\"smallFull\">
                                                                              <td class=\"text_padding_mobile_0 cellFull  noMoreHeight\" align=\"left\" style=\"width:100%;border-collapse: collapse;text-align:left;height:71px;vertical-align:top\">
                                                                                 <div style=\"text-align:left;font-size:14px;font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#adb8bd;line-height:130%;width:100%;;display: block !important;\"></div>
                                                                              </td>
                                                                           </tr>
                                                                        </tbody>
                                                                     </table>
                                                                  </td>
                                                               </tr>
                                                            </tbody>
                                                         </table>
                                                      </td>
                                                      <td style=\"width:50px;background-color:#3e494f;\" class=\"out_hide\"></td>
                                                   </tr>
                                                </tbody>
                                             </table>
                                          </td>
                                       </tr>
                                    </tbody>
                                 </table>
                                 <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"width:100%;display:block;margin:0 auto;border:none;max-width:640px;table-layout:fixed;\">
                                    <tbody style=\"width:100%;display:block;\">
                                       <tr class=\"blockClass holderMax\" style=\"width:640px;display:block\">
                                          <td class=\"blockClassPadding\" style=\"width:100%;display:block;vertical-align:middle;padding:0px;background-color:#3e494f;\">
                                             <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"border: none; display: block;min-height:153px\">
                                                <tbody style=\"width:100%;display:block\">
                                                   <tr style=\"width:100%;display:block\">
                                                      <td style=\"width:50px;background-color:#3e494f;\" class=\"out_hide\"></td>
                                                      <td style=\" vertical-align:top;text-align:left;width:255px;  background-color:transparent; overflow:hidden;\" class=\"cellFull  layout_width_39_84   outlook_width_255 \">
                                                         <table para=\"complexContainerBorder\" class=\"outlook_width_255 \" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"display:block!important\">
                                                            <tbody style=\"width:100%;display:block\">
                                                               <tr style=\"width:100%;display:block;\">
                                                                  <td class=\"outlook_width_255   wild_full superWidthClass text_padding_0 \" style=\"border-collapse:collapse;vertical-align:top;padding:8px 0px 8px 0px;background-color:transparent;max-width:255px;display:inline-block;\">
                                                                     <table class=\"cellFull chromeFix\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"width:100%;max-width:255px\">
                                                                        <tbody class=\"smallFull\">
                                                                           <tr style=\"width:100%;\" class=\"smallFull\">
                                                                              <td class=\"text_padding_mobile_0 cellFull  noMoreHeight\" align=\"left\" style=\"width:100%;border-collapse: collapse;text-align:left;height:137px;vertical-align:top\">
                                                                                 <div style=\"text-align:left;font-size:14px;font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#adb8bd;line-height:130%;width:100%;;display: block !important;\">Let us to help you.</div>
                                                                              </td>
                                                                           </tr>
                                                                        </tbody>
                                                                     </table>
                                                                  </td>
                                                               </tr>
                                                            </tbody>
                                                         </table>
                                                      </td>
                                                      <td style=\"width:30px;background-color:#3e494f;\" class=\"out_hide\"></td>
                                                      <td style=\" vertical-align:top;text-align:left;width:255px;  background-color:transparent; overflow:hidden;\" class=\"cellFull  layout_width_39_84   outlook_width_255 \">
                                                         <table para=\"complexContainerBorder\" class=\"outlook_width_255 \" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"display:block!important\">
                                                            <tbody style=\"width:100%;display:block\">
                                                               <tr style=\"width:100%;display:block;\">
                                                                  <td class=\"outlook_width_255   wild_full superWidthClass text_padding_0 \" style=\"border-collapse:collapse;vertical-align:top;padding:8px 0px 8px 0px;background-color:transparent;max-width:255px;display:inline-block;\">
                                                                     <table class=\"cellFull chromeFix\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"width:100%;max-width:255px\">
                                                                        <tbody class=\"smallFull\">
                                                                           <tr style=\"width:100%;\" class=\"smallFull\">
                                                                              <td class=\"text_padding_mobile_0 cellFull  noMoreHeight\" align=\"left\" style=\"width:100%;border-collapse: collapse;text-align:left;height:137px;vertical-align:top\">
                                                                                 <div style=\"text-align:left;font-size:18px;font-family: Roboto Slab , Arial, Helvetica, serif;text-decoration:none;color:#adb8bd;line-height:129%;width:100%;;display: block !important;\"><span style=\"color: #ffffff;\"><span style=\"color: #adb8bd;\">Mobile: &nbsp;</span>+45 123 45 67<br>
                                                                                    <br><span style=\"color: #adb8bd;\">
                                                                                    E-mail: &nbsp;</span>info@marketips.com</span>
                                                                                 </div>
                                                                              </td>
                                                                           </tr>
                                                                        </tbody>
                                                                     </table>
                                                                  </td>
                                                               </tr>
                                                            </tbody>
                                                         </table>
                                                      </td>
                                                      <td style=\"width:50px;background-color:#3e494f;\" class=\"out_hide\"></td>
                                                   </tr>
                                                </tbody>
                                             </table>
                                          </td>
                                       </tr>
                                    </tbody>
                                 </table>
                                 <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"width:100%;display:block;margin:0 auto;border:none;max-width:640px;table-layout:fixed;\">
                                    <tbody style=\"width:100%;display:block;\">
                                       <tr class=\"blockClass holderMax\" style=\"width:640px;display:block\">
                                          <td class=\"blockClassPadding\" style=\"width:100%;display:block;vertical-align:middle;padding:0px;background-color:transparent;\">
                                             <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"border: none; display: block;min-height:149px\">
                                                <tbody style=\"width:100%;display:block\">
                                                   <tr style=\"width:100%;display:block\">
                                                      <td style=\"width:50px;background-color:transparent;\" class=\"out_hide\"></td>
                                                      <td style=\" vertical-align:top;text-align:center;width:540px;  background-color:transparent; overflow:hidden;\" class=\"cellFull  layout_width_84_37   outlook_width_540 \">
                                                         <table para=\"complexContainerBorder\" class=\"outlook_width_540 \" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"display:block!important\">
                                                            <tbody style=\"width:100%;display:block\">
                                                               <tr style=\"width:100%;display:block;\">
                                                                  <td class=\"outlook_width_540   wild_full  text_padding_0 \" style=\"border-collapse:collapse;vertical-align:top;padding:8px 0px 8px 0px;background-color:transparent;max-width:540px;display:inline-block;\">
                                                                     <table class=\"cellFull chromeFix\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" style=\"width:100%;max-width:540px\">
                                                                        <tbody class=\"smallFull\">
                                                                           <tr style=\"width:100%;\" class=\"smallFull\">
                                                                              <td class=\"text_padding_mobile_0 cellFull  noMoreHeight\" align=\"center\" style=\"width:100%;border-collapse: collapse;text-align:center;height:133px;vertical-align:middle\">
                                                                                 <div style=\"text-align:center;font-size:14px;font-family:Arial, Helvetica, sans-serif;text-decoration:none;color:#adb8bd;line-height:130%;width:100%;;display: block !important;\"><span style=\"font-size:9px\">
                                                                                    <span style=\"font-size: 12px; color: #adb8bd;\">We hope you like our newsletters. If you don't, <a href=\"#0\" typ=\"2\" style=\"color: #ffffff; text-decoration: none;\"><span>simply unsubscribe.</span></a><span style=\"color: #ffffff;\"></span><br>
                                                                                    <br>
                                                                                    Message sent by YourName company: YourCompany LTD United Kingdom at Address, City. <br>
                                                                                    Phone Number. +44 12 3456 7890, email: support@yourcompany.com, <br>
                                                                                    www: youtcompany.com Registration Number 00000000.
                                                                                    </span>
                                                                                    </span>
                                                                                 </div>
                                                                              </td>
                                                                           </tr>
                                                                        </tbody>
                                                                     </table>
                                                                  </td>
                                                               </tr>
                                                            </tbody>
                                                         </table>
                                                      </td>
                                                      <td style=\"width:50px;background-color:transparent;\" class=\"out_hide\"></td>
                                                   </tr>
                                                </tbody>
                                             </table>
                                          </td>
                                       </tr>
                                    </tbody>
                                 </table>
                                 <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"width:100%;display:block;margin:0 auto;border:none;max-width:640px;table-layout:fixed;\">
                                    <tbody style=\"width:100%;display:block;\">
                                       <tr style=\"width:100%;display:block\">
                                       </tr>
                                    </tbody>
                                 </table>
                                 <!--[if mso]>
                              </td>
                           </tr>
                        </table>
                        <![endif]--><!--[if mso]>
                     </td>
                  </tr>
               </table>
               <![endif]-->
            </div>
            </body>
            </html>

        ";

        //echo "<br> rrr" . $message . " ppp";

       // print_r($user);


        //Send the email
        if($user->uid!=0 || $user->name != "" || $user->mail!=null){
            send($user->mail, $message, $user->name);
        }


    }*/



    return $vars;
}
